FROM ubuntu:24.04

ARG PLATFORM
ARG FLAVOR
ARG DOCKER_REGISTRY

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
       build-essential \
       cryptsetup-bin \
       curl \
       default-libmysqlclient-dev \
       git \
       gpg \
       libffi-dev \
       libmbedtls14 \
       libmysqlclient-dev \
       libnuma-dev \
       musl \
       openssl \
       pkg-config \
       python3 \
       python3-dev \
       python3-pandas \
       python3-pip \
       python3-venv \
       sudo \
       tzdata \
       unzip \
       wget \
    && useradd zircon-tests \
    && ln -fs /usr/share/zoneinfo/CET /etc/localtime \
    && dpkg-reconfigure -f noninteractive tzdata \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists

VOLUME /tmp/build

COPY requirements_frozen.txt /tmp/build/requirements_frozen.txt
RUN pip3 install --break-system-packages --ignore-installed --force-reinstall -r /tmp/build/requirements_frozen.txt && rm -fdr /tmp/build/*

# To update requirements_frozen.txt: comment out above 2 commands, and uncomment below 2 commands, then `base64 -d > requirements_frozen.txt`
#COPY requirements.txt /tmp/build/requirements.txt
#RUN pip3 install -r /tmp/build/requirements.txt && pip3 freeze | base64 -w0 && exit 1

# Newer versions of Docker support a --chown flag to the COPY directive
# that let you change file ownership without creating an extra container
# layer, but we're still using an older version of Docker without this support.
COPY tests /home/zircon-tests/tests/
COPY docker-credential-ecr-login /usr/local/bin/
COPY docker-config.json /home/zircon-tests/.docker/config.json
COPY container-converter /home/zircon-tests/tests/tools/converter/bin/container-converter

# Copy custom OVMF
COPY tdx/OVMF.inteltdx.fd /opt/fortanix/enclave-os/blobs/OVMF.inteltdx.fd

# Copy gpu disabled artifacts
COPY kernel_disabled_gpu/init /opt/fortanix/enclave-os/blobs/kernel_disabled_gpu/init
COPY tdx/kernel_disabled_gpu/.config /opt/fortanix/enclave-os/blobs/kernel_disabled_gpu/bzImage.config
COPY tdx/kernel_disabled_gpu/bzImage /opt/fortanix/enclave-os/blobs/kernel_disabled_gpu/bzImage

# Copy gpu enabled artifacts
COPY kernel_enabled_gpu/init /opt/fortanix/enclave-os/blobs/kernel_enabled_gpu/init
COPY tdx/kernel_enabled_gpu/.config /opt/fortanix/enclave-os/blobs/kernel_enabled_gpu/bzImage.config
COPY tdx/kernel_enabled_gpu/bzImage /opt/fortanix/enclave-os/blobs/kernel_enabled_gpu/bzImage
COPY tdx/kernel_enabled_gpu/nvidia-uvm.ko /opt/fortanix/enclave-os/blobs/kernel_enabled_gpu/nvidia-uvm.ko
COPY tdx/kernel_enabled_gpu/nvidia.ko /opt/fortanix/enclave-os/blobs/kernel_enabled_gpu/nvidia.ko
COPY tdx/kernel_enabled_gpu/nvidia-drm.ko /opt/fortanix/enclave-os/blobs/kernel_enabled_gpu/nvidia-drm.ko
COPY tdx/kernel_enabled_gpu/nvidia-modeset.ko /opt/fortanix/enclave-os/blobs/kernel_enabled_gpu/nvidia-modeset.ko

# Copy the parts that change often last to reuse layers
COPY parent-base.tar enclave-base.tar /app/

RUN mkdir /home/zircon-tests/tests/codegen && mkdir /home/zircon-tests/tests/codegen/python
COPY generated_string_table.py /home/zircon-tests/tests/codegen/python

RUN chown -R zircon-tests:zircon-tests /home/zircon-tests

# This ensures that zircon-tests is not asked for a password
# when it runs commands using sudo. Needed to allow converting
# tdx apps with filesystem features (which needs sudo privileges
# for operations such as a file mount)
RUN usermod -aG sudo zircon-tests && \
    echo "zircon-tests ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
    visudo -c

WORKDIR /home/zircon-tests/tests

ENV PYTHONPATH="${PYTHONPATH}:/home/zircon-tests/tests/tools/app-test-infra/python:/home/zircon-tests/tests/codegen/python" \
    PLATFORM=tdx \
    FLAVOR=$FLAVOR \
    DOCKER_REGISTRY=$DOCKER_REGISTRY \
    IS_NITRO=false

ENTRYPOINT [ "/home/zircon-tests/tests/tools/app-test-infra/bin/tests-container-entry.sh" , "--app-test-salmiac", "--frequency", "daily", "--container-platform", "tdx"]
