[workspace]

members = [
    "shared",
    "parent",
    "enclave",
]

[workspace.dependencies]
serde_json = "1.0"

[patch.crates-io]
serde_json = { git = "https://github.com/fortanix/serde-json.git", branch = "base64_bytes" }
