[workspace]

members = [
    "enclave",
    "parent",
    "shared",
]

[workspace.dependencies]
em-app = { version = "0.5.1" }
em-client = { version = "4.0.1" }
attestation-client = { git = "ssh://git@github.com/fortanix/attestation.git", branch = "dlegalov/RTE-1094-client-csr-param-api-improvements", package = "client" }
