[package]
name = "enclave-startup"
version = "0.1.0"
authors = ["Fortanix, Inc."]
edition = "2018"
license = "MPL-2.0"
repository = "https://github.com/fortanix/salmiac"


[dependencies]
env_logger = "0.7"
log = "0.4"
nix = { version = "0.26.1", features = ["hostname"] }
users = "0.11.0"
