[package]
name = "enclave-startup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.7"
log = "0.4"
nix = { version = "0.26.1", features = ["hostname"] }
users = "0.11.0"
