[workspace]

members = [
    "api-model",
    "client",
    "client-generator",
    "server"
]

[patch.crates-io]
mbedtls = { git = "https://github.com/fortanix/rust-mbedtls", branch = "mz/async-support"}
