name: Build Solution

on:
  workflow_call:
    secrets:
      FORTANIX_API_KEY:
        required: true
      OVERLAYFS_UNIT_TEST_API_KEY:
        required: true
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
      - name: Pull main repository
        uses: actions/checkout@v3
        with:
          repository: fortanix/salmiac

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          targets: x86_64-unknown-linux-musl, x86_64-unknown-linux-gnu
          toolchain: nightly-2024-11-21

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpcap-dev

      # The 3 steps below to install clang, cmake and set LD_LIBRARY_PATH
      # are needed to ensure our code compiles and works on ubuntu 24.
      # These steps can be replaced with apt package installs once bindgen
      # crate is updated in salmiac
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "12.0"

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "3.28"

      - name: Set LIBCLANG_PATH correctly
        run: |
          echo "Original LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
          export LIBCLANG_PATH=$(echo "$LD_LIBRARY_PATH" | tr -d ':')
          echo "LIBCLANG_PATH=$LIBCLANG_PATH" >> $GITHUB_ENV

      - name: Build Rust code
        run: |
          ./build-converter.sh

      - name: Run Rust unit tests
        env:
          FORTANIX_API_KEY: ${{ secrets.FORTANIX_API_KEY }}
          OVERLAYFS_UNIT_TEST_API_KEY: ${{ secrets.OVERLAYFS_UNIT_TEST_API_KEY }}
        run: |
          ./unit-test-solution.sh
