name: Build and publish Docker Images

on:
  push:
    branches: [ "master" ]
    paths:
      - 'docker/enclave-base/**'
      - 'docker/parent-base/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'docker/enclave-base/**'
      - 'docker/parent-base/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Pull main repository
        uses: actions/checkout@v3
        with:
          repository: fortanix/salmiac

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker images
        run: |
          cd docker/enclave-base
          docker build -t fortanix/enclave-base .

          cd ../parent-base
          docker build -t fortanix/parent-base .

      - name: Push docker images
        run: |
          docker push fortanix/enclave-base
          docker push fortanix/parent-base
