name: Build and publish Docker Images

on:
  push:
    branches: [ "master" ]
    paths:
      - 'docker/enclave-base/**'
      - 'docker/parent-base/**'
  pull_request:
    branches: [ "master" ]
    types:
      - closed
      - opened
    paths:
      - 'docker/enclave-base/**'
      - 'docker/parent-base/**'

jobs:
  build-docker-images:
    runs-on: ubuntu-20.04
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'edited')
    steps:
      - name: Pull main repository
        uses: actions/checkout@v3
        with:
          repository: fortanix/salmiac

      - name: Build docker images
        run: |
          docker build docker/enclave-base -t enclave-base
          docker build docker/parent-base -t parent-base
          docker rmi enclave-base parent-base