name: Build and publish Docker Images

on:
  push:
    branches: [ "master" ]
    paths:
      - 'docker/**'
  pull_request:
    branches: [ "master" ]
    types:
      - closed
      - opened
      - synchronize
    paths:
      - 'docker/**'

jobs:
  build-docker-images:
    runs-on: ubuntu-24.04
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize')
    steps:
      - name: Pull main repository
        uses: actions/checkout@v3
        with:
          repository: fortanix/salmiac

      - name: Build docker images
        run: |
          docker build docker/enclave-base -t enclave-base
          docker build docker/enclave-base-snp -t enclave-base-snp
          docker build docker/parent-base -t parent-base
          docker build \
            --build-context parent-base=docker/parent-base \
            -t parent-base-snp \
            docker/parent-base-snp
          docker rmi enclave-base enclave-base-snp parent-base parent-base-snp
