name: Build and publish Docker Images

on:
  push:
    branches: [ "master" ]
    paths:
      - 'docker/**'
  pull_request:
    branches: [ "master" ]
    types:
      - closed
      - opened
      - synchronize
    paths:
      - 'docker/**'

jobs:
  build-docker-images:
    runs-on: ubuntu-24.04
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize')
    steps:
      - name: Pull main repository
        uses: actions/checkout@v3
        with:
          repository: fortanix/salmiac

      - name: Build docker images
        run: |
          docker build --no-cache docker/enclave-base -t enclave-base
          docker build --no-cache docker/enclave-base-gpu -t enclave-base-gpu
          docker build --no-cache docker/nitro/parent-base -t parent-base-nitro
          docker build --no-cache \
            --build-context parent-base=docker/nitro/parent-base \
            -t parent-base-qemu \
            docker/qemu/parent-base
          docker rmi enclave-base enclave-base-gpu parent-base-nitro parent-base-qemu
