name: Build Solution

on:
  workflow_call:
    secrets:
      FORTANIX_API_KEY:
        required: true
      OVERLAYFS_UNIT_TEST_API_KEY:
        required: true
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - name: Pull main repository
        uses: actions/checkout@v3
        with:
          repository: fortanix/salmiac

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          targets: x86_64-unknown-linux-musl, x86_64-unknown-linux-gnu
          toolchain: nightly-2024-11-21

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpcap-dev

      - name: Build Rust code
        run: |
          ./build-converter.sh

      - name: Run Rust unit tests
        env:
          FORTANIX_API_KEY: ${{ secrets.FORTANIX_API_KEY }}
          OVERLAYFS_UNIT_TEST_API_KEY: ${{ secrets.OVERLAYFS_UNIT_TEST_API_KEY }}
        run: |
          ./unit-test-solution.sh
