name: Entry point workflow, which runs on every PR

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - name: Pull main repository
        uses: actions/checkout@v3

      - name: Pull submodules
        uses: actions/checkout@v3
        with:
          repository: fortanix/app-test-infra-test
          token: ${{ secrets.PAT }}
          path: tools/app-test-infra

      call-build-solution:
        uses: ./.github/workflows/build-solution.yml@main
        secrets: inherit
